// Code generated by eventcode -decl componentmgr_event.go -package foundation -core ; DO NOT EDIT.
package core

func EmitEventCompMgrAddComponents[T any](event IEvent, compMgr T, components []Component) {
	if event == nil {
		panic("nil event")
	}
	event.Emit(func(delegate FastIFace) bool {
		Fast2IFace[EventCompMgrAddComponents[T]](delegate).OnCompMgrAddComponents(compMgr, components)
		return true
	})
}

func EmitEventCompMgrRemoveComponent[T any](event IEvent, compMgr T, component Component) {
	if event == nil {
		panic("nil event")
	}
	event.Emit(func(delegate FastIFace) bool {
		Fast2IFace[EventCompMgrRemoveComponent[T]](delegate).OnCompMgrRemoveComponent(compMgr, component)
		return true
	})
}
