// Code generated by eventcode -decl entitymgr_event.go -package foundation -core ; DO NOT EDIT.
package core

func EmitEventEntityMgrAddEntity[T any](event IEvent, entityMgr T, entity Entity) {
	if event == nil {
		panic("nil event")
	}
	event.Emit(func(delegate FastIFace) bool {
		Fast2IFace[EventEntityMgrAddEntity[T]](delegate).OnEntityMgrAddEntity(entityMgr, entity)
		return true
	})
}

func EmitEventEntityMgrRemoveEntity[T any](event IEvent, entityMgr T, entity Entity) {
	if event == nil {
		panic("nil event")
	}
	event.Emit(func(delegate FastIFace) bool {
		Fast2IFace[EventEntityMgrRemoveEntity[T]](delegate).OnEntityMgrRemoveEntity(entityMgr, entity)
		return true
	})
}

func EmitEventEntityMgrEntityAddComponents[T any](event IEvent, entityMgr T, entity Entity, components []Component) {
	if event == nil {
		panic("nil event")
	}
	event.Emit(func(delegate FastIFace) bool {
		Fast2IFace[EventEntityMgrEntityAddComponents[T]](delegate).OnEntityMgrEntityAddComponents(entityMgr, entity, components)
		return true
	})
}

func EmitEventEntityMgrEntityRemoveComponent[T any](event IEvent, entityMgr T, entity Entity, component Component) {
	if event == nil {
		panic("nil event")
	}
	event.Emit(func(delegate FastIFace) bool {
		Fast2IFace[EventEntityMgrEntityRemoveComponent[T]](delegate).OnEntityMgrEntityRemoveComponent(entityMgr, entity, component)
		return true
	})
}
