// Code generated by eventcode -decl entity_event.go -package foundation -core ; DO NOT EDIT.
package core

func EmitEventEntityDestroySelf(event IEvent, entity Entity) {
	if event == nil {
		panic("nil event")
	}
	event.Emit(func(delegate FastIFace) bool {
		Fast2IFace[EventEntityDestroySelf](delegate).OnEntityDestroySelf(entity)
		return true
	})
}
