// Code generated by eventcode -decl runtime_event.go -package foundation -core ; DO NOT EDIT.
package core

func EmitEventUpdate(event IEvent) {
	if event == nil {
		panic("nil event")
	}
	event.Emit(func(delegate FastIFace) bool {
		Fast2IFace[EventUpdate](delegate).Update()
		return true
	})
}

func EmitEventLateUpdate(event IEvent) {
	if event == nil {
		panic("nil event")
	}
	event.Emit(func(delegate FastIFace) bool {
		Fast2IFace[EventLateUpdate](delegate).LateUpdate()
		return true
	})
}
