// Code generated by eventcode -decl runtimecontext_event.go -package core -core  -exportemit=false; DO NOT EDIT.
package core

func emitEventPushSafeCallSegment(event IEvent, segment func()) {
	if event == nil {
		panic("nil event")
	}
	event.Emit(func(delegate FastIFace) bool {
		Fast2IFace[EventPushSafeCallSegment](delegate).OnPushSafeCallSegment(segment)
		return true
	})
}
