// Code generated by eventcode -decl runtime_event.go -package core -core  -exportemit=false; DO NOT EDIT.
package core

func emitEventUpdate(event IEvent) {
	if event == nil {
		panic("nil event")
	}
	event.Emit(func(delegate FastIFace) bool {
		Fast2IFace[EventUpdate](delegate).Update()
		return true
	})
}

func emitEventLateUpdate(event IEvent) {
	if event == nil {
		panic("nil event")
	}
	event.Emit(func(delegate FastIFace) bool {
		Fast2IFace[EventLateUpdate](delegate).LateUpdate()
		return true
	})
}
